async function DeciderException() {
  throw new Error('SomeFailure')
}

export default DeciderException
